In [1]:
import numpy as np

In [2]:
#Creat arrays of ones, but with different dt
int_ones = np.ones((2,2), dtype = np.int8)

In [3]:
int_ones

array([[1, 1],
       [1, 1]], dtype=int8)

In [50]:
vec1 = np.random.randint(0, 10, (5))
vec1

array([5, 0, 8, 0, 8])

In [56]:
vec1.dtype

dtype('int8')

In [54]:
#将vec1的数据类型转换为int8
vec1 =np.array(vec1, dtype =np.int8)
vec1

array([5, 0, 8, 0, 8], dtype=int8)

In [55]:
vec1.dtype

dtype('int8')

In [57]:
print(vec1)

[5 0 8 0 8]


In [71]:
#新建随机多维数据集
arr1 = np.random.randint(0, 10, (2, 3, 4))
arr1

array([[[0, 9, 2, 9],
        [5, 3, 9, 2],
        [0, 8, 6, 2]],

       [[8, 0, 0, 2],
        [4, 2, 2, 0],
        [2, 7, 2, 3]]])

In [62]:
arr1.dtype

dtype('int32')

In [63]:
#将arr1的数据类型转换为int8
arr1 = np.array(arr1, dtype = np.int8)
arr1

array([[[7, 5, 4, 8],
        [2, 5, 8, 0],
        [3, 5, 4, 5]],

       [[8, 0, 7, 1],
        [4, 6, 4, 5],
        [6, 4, 3, 5]]], dtype=int8)

In [72]:
arr2=np.array([[(1,2,3),(4,5,6)],[(3,np.nan,1),(4,5,6)]])
print(arr2)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 3. nan  1.]
  [ 4.  5.  6.]]]


In [74]:
arr2_copy = arr2.copy()
arr2_copy

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 3., nan,  1.],
        [ 4.,  5.,  6.]]])

In [75]:
arr2_copy[0,0,0] = 250
arr2_copy

array([[[250.,   2.,   3.],
        [  4.,   5.,   6.]],

       [[  3.,  nan,   1.],
        [  4.,   5.,   6.]]])

In [76]:
arr2

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 3., nan,  1.],
        [ 4.,  5.,  6.]]])

In [77]:
%pwd

'D:\\Anaconda3\\envs\\shnu\\demo\\Numpy和Pandas数据分析使用指南'

In [78]:
#保存arr2
np.save('my_array', arr2)

In [79]:
arr2_new = np.load('my_array.npy')
print(arr2_new)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 3. nan  1.]
  [ 4.  5.  6.]]]


In [80]:
mat1=np.random.randn(5,5)
print(mat1)

[[ 1.05403198  0.16687131 -1.6526444   0.74226101 -1.892015  ]
 [ 1.15047781  0.40297586  1.14410747  0.25219232 -0.57457838]
 [-0.90262592  1.17429031  1.7228443  -0.27900631 -0.46573076]
 [ 0.99825868  0.61421318 -1.45158334 -0.1640655  -1.87770805]
 [-0.22737754  0.35571644 -0.27436631 -0.79939051 -0.18805414]]


In [81]:
#保存mat1
np.savetxt('mat1.csv', mat1, delimiter = ',')

In [84]:
#查看mat1
mat1file= open('mat1.csv', 'r')
for l in mat1file:
    print(l)

1.054031978980027429e+00,1.668713066842735238e-01,-1.652644403805453743e+00,7.422610090586085896e-01,-1.892014998682021165e+00

1.150477805065013737e+00,4.029758565876834786e-01,1.144107468610899625e+00,2.521923221406320859e-01,-5.745783802977060262e-01

-9.026259202182836949e-01,1.174290308725689957e+00,1.722844297642379008e+00,-2.790063120815992614e-01,-4.657307633548777304e-01

9.982586799360602114e-01,6.142131806109596415e-01,-1.451583342351153938e+00,-1.640655022568339449e-01,-1.877708053619857376e+00

-2.273775438055784248e-01,3.557164381223567595e-01,-2.743663066207479018e-01,-7.993905063028946545e-01,-1.880541369950129438e-01



In [86]:
mat1file.close()

In [ ]:
#加载mat1
mat1_new=np.loadtxt('mat1.csv', delimiter = ',')
print(mat1_new)