# 三、NumPy数组上的运算
-----------------


## 现在，我们知道如何创建 NumPy 数组，我们可以讨论切片 NumPy 数组的重要主题，以便访问和操作数组数据的子集。 在本章中，我们将介绍每个 NumPy 用户应了解的有关数组切片，算术，带有数组的线性代数以及采用数组方法和函数的知识。

## 显式选择元素
-------------

### 如果您知道如何选择 Python 列表的子集，那么您将了解有关ndarray切片的大部分知识。 与索引对象的元素相对应的被索引数组元素在新数组中返回。 索引编制的最重要方面是要记住存在多个维度，并且索引编制方法应能够处理这些其他维度。

### 明确选择元素时，请记住以下几点：

- 阵列的切片与列表的切片非常相似；只需记住可能有多个维度。(array slicing strongly resembles slicing lists; just remember there may be more than one dimensions)
- 对于长度为5的一维数组arr1，我们可以用arr1\[\[0,2,3\]\]来选择元素（列表可以用元组代替）;(for a one-dimensional array arr1 of length 5, we can select element with arr1\[\[0,2,3\]\](the list could be replaced with a tuple))
- 一个5x3的数组arr2可以像arr2\[\[0,2,3\]\]\[\[1,2\]\]那样进行子集，但对于ndarrays来说，这种语法并不可取;(A 5x3 array arr2 could be subset like arr2\[\[0,2,3\]\]\[\[1,2\]\], but this syntax is not preferred for ndarrays)
- 一个等价的和首选的子集是：arr2\[\[0,2,3\],\[1,2\]\]；逗号分隔维度。(an equivalent and preferred subsetting would be: arr2\[\[0,2,3\],\[1,2\]\]; the comma separates dimensions).
- 用逗号分隔不同维度的索引对象； 第一个逗号之前的对象显示了如何索引第一维。 在第一个逗号之后是第二个维度的索引，在第二个逗号之后是第三个维度的索引，依此类推。

## 用冒号切片数组
----------------

### 使用冒号索引ndarray对象的工作类似于使用冒号索引列表。 只要记住，现在有多个维度。 请记住，当冒号之前或之后的点留为空白时，Python 会将索引视为扩展到维的开始或结束。 可以指定第二个冒号，以指示 Python 跳过每隔一行或反转行的顺序，具体取决于第二个冒号下的数目。

### 使用冒号对数组进行切片时，需要记住以下几点：


In [1]:
#加载numpy并创建一个数组
import numpy as np

In [2]:
arr1= np.array([[["Joey","Bob","Sarah"],
                ["Margaret","Rachel","Jim"],
                ["Wayne","Joey","Liam"]],

               [["Max","Maxine","Richard"],
                ["Harold","Curtis","Simon"],
                ["Bob","Liam","Simon"]],

               [["Wayne","Sarah","Lucy"],
                ["Lucy","Kurtis","Yu"],
                ["Joey","Lex","Alex"]]])

print(arr1)


[[['Joey' 'Bob' 'Sarah']
  ['Margaret' 'Rachel' 'Jim']
  ['Wayne' 'Joey' 'Liam']]

 [['Max' 'Maxine' 'Richard']
  ['Harold' 'Curtis' 'Simon']
  ['Bob' 'Liam' 'Simon']]

 [['Wayne' 'Sarah' 'Lucy']
  ['Lucy' 'Kurtis' 'Yu']
  ['Joey' 'Lex' 'Alex']]]


In [13]:
#获取数组的维度
arr1.shape

(3, 3, 3)

In [3]:
arr2=arr1[:,:,0].copy()#新建副本，不改变原数组
print(arr2)

[['Joey' 'Margaret' 'Wayne']
 ['Max' 'Harold' 'Bob']
 ['Wayne' 'Lucy' 'Joey']]


In [21]:
arr2.shape

(3, 3)

In [14]:
#补充知识 维度问题
a = np.arange(120).reshape(2,3,4,5)
#得到shape为(2,3,4,5)的张量a，输出a为

In [15]:
print(a)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]


## 对应a[第0维,第1维,第2维,第3维]，假如我要输出a[:,2,:,4],从后往前看就是，取出最后一维(第三维)的第4列（红色框），取出第2维所有列，取出第1维的第2列（黄色框），取出第0维的所有列
--https://blog.csdn.net/qq_55655082/article/details/127400929

In [0]:
b=a[:,2,:,4]
b

## 同时也可以看到，输出结果的shape变成了两维。因此对于一个numpy多维array，[:,:,:,:,…,:]，将多少个“:”替换为具体的值，最后的结果就降低几维。

In [20]:
b.shape

(2, 3, 4)

In [54]:
#back
print(arr2)
#手动选择“十字”元素
print(arr2[[1,1,1,0,2],[0,1,2,1,1]])

[['Joey' 'Margaret' 'Wayne']
 ['Max' 'Harold' 'Bob']
 ['Wayne' 'Lucy' 'Joey']]
['Max' 'Harold' 'Bob' 'Margaret' 'Lucy']


In [26]:
#从左上角选择元素
#upper-left corner
print(arr2[:2,:2])

[['Joey' 'Monica']
 ['Max' 'Monica']]


In [28]:
#从右下角选择元素
print(arr2[1:,1:])

[['Monica' 'Bob']
 ['Alex' 'Jim']]


In [29]:
#从中间一列选择元素，但不展开
print(arr2[:,[1]])

[['Monica']
 ['Monica']
 ['Alex']]


In [30]:
#中间列的最后两行
#last two rows of middle column
print(arr2[1:,1])

['Monica' 'Alex']


In [0]:
#反转行顺序
#Reverse row order
print(arr2[::-1])

## b = a[i:j:s]. 注意:当s<0时，i缺省时，默认为-1. j缺省时，默认为-len(a)-1,所以a[::-1]相当于 a[-1:-len(a)-1:-1]，也就是从最后一个元素到第一个元素复制一遍，即倒序。

In [0]:
#选择奇数列
#select odd-number columns
print(arr2[:, 0:3:2])

## arr [start: end: step]，start缺省时，从左边index=0开始，end缺省时，取到最右边index=len(arr)-1，step缺省时，默认为+1。
——https://blog.csdn.net/weixin_41888257/article/details/104359002

## 转到更复杂的的三维数组,
## 选择一个2x2x2的角立方体
## choose a 2x2x2 corner cube

In [39]:
print(arr1)

arr1.shape

[[['Joey' 'Chandler' 'Ross']
  ['Monica' 'Phoebe' 'Rachel']
  ['Wayne' 'Gretzky' 'Messier']]

 [['Max' 'Chandler' 'Ross']
  ['Monica' 'Phoebe' 'Rachel']
  ['Bob' 'Lex' 'Luther']]

 [['Lucy' 'Yu' 'Han']
  ['Alex' 'Sarah' 'Lily']
  ['Jim' 'Tom' 'Jack']]]


(3, 3, 3)

In [36]:
#choose a 2x2x2 corner cube
#top-left corner
print(arr1[:2,:2,:2])

[[['Joey' 'Chandler']
  ['Monica' 'Phoebe']]

 [['Max' 'Chandler']
  ['Monica' 'Phoebe']]]


In [42]:
print(arr1[:,1,:].shape)# Not three dimensions

(3, 3)


我们可以看到该中间切片是二维数组。 因此，如果我们希望保留维数，那么另一种方法是使用 NumPy 中的新轴对象插入一个额外的维数：

In [43]:
# 选择中间片，但保留维度
# select middle slice, but keep dimensions
print(arr1[:,1,np.newaxis,:])

[[['Monica' 'Phoebe' 'Rachel']]

 [['Monica' 'Phoebe' 'Rachel']]

 [['Alex' 'Sarah' 'Lily']]]


我们看到这个对象实际上是三维的：

In [45]:
print(arr1[:,1,np.newaxis,:].shape)

(3, 1, 3)


尽管事实上其中的一个维度长度为1

## 高级索引
-----------

现在让我们讨论更高级的索引技术。 我们可以使用其他`ndarray`为`ndarray`对象建立索引。 我们可以使用包含与我们希望选择的`ndarray`的索引对应的整数的`ndarray`对象或布尔值的`ndarray`对象来切片`ndarray`对象，其中值`true`表示切片中应包含一个单元格。

选择不是`Wayne`的`arr2`元素，这是结果：

In [46]:
# 选择所有不属于Wayne的元素
# Select all entries that are not Wayne
print(arr2[arr2 != "Wayne"])

['Joey' 'Monica' 'Max' 'Monica' 'Bob' 'Lucy' 'Alex' 'Jim']


`Wayne`不包括在选择中，这是为执行该索引而生成的数组：

In [47]:
# 对布尔数组索引的浅探
# A peek at the indexing boolean array
print(arr2 != "Wayne")

[[ True  True False]
 [ True  True  True]
 [ True  True  True]]


除了内容为`Wayne`的地方，到处都是`True`。

另一种更高级的技术是使用整数数组进行选择，以标识所需的元素。 因此，在这里，我们将创建两个用于切片的数组：

In [53]:
# 高效的选择一个存放角落数据的数组
# Select, effectively, an array holding the data in the corners
idx0 = np.array([[0,0],
                 [2,-2]])
idx1 = np.array([[0,2],
                 [0,2]])
print(arr2[idx0,idx1])

[['Joey' 'Wayne']
 ['Wayne' 'Bob']]


第一个数组中的第一个 0 表示第一个坐标为零，第二个数组中的第一个 0 表示第二个坐标为零，这由这两个数组列出的顺序指定。因此，所得数组的第一行和第一列的元素为`[0, 0]`。 在第一行和第二列中，我们有原始数组中的元素`[0, 2]`。 然后，在第二行和第一列中，我们具有原始数组的第三行和第一列中的元素。 注意，这是`Wayne`。

然后，我们有了原始数组的第三行和第三列中的元素，该元素对应于`Bob`。

让我们来看一下更复杂的数组。 例如，我们可以看到`arr1`以外的所有条目`Curtis`:

In [55]:
# 所有不属于Curtis的元素
# All entries that are not Curtis
print(arr1[arr1 != "Curtis"])

['Joey' 'Bob' 'Sarah' 'Margaret' 'Rachel' 'Jim' 'Wayne' 'Joey' 'Liam'
 'Max' 'Maxine' 'Richard' 'Harold' 'Simon' 'Bob' 'Liam' 'Simon' 'Wayne'
 'Sarah' 'Lucy' 'Lucy' 'Kurtis' 'Yu' 'Joey' 'Lex' 'Alex']


这是索引数组的样子：

In [56]:
# A peek at the indexing array
print(arr1 != "Curtis")

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True False  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]


在这里，我们看到了一个更为复杂的切片方案：

In [71]:
# 得到一个2x2x2的角元素矩阵
# Get a 2x2x2 matrix of the corner elements

#Row indices 行索引
idx0 = np.array([[[0,0],
                  [0,0]],

                 [[2,2],
                 [2,2]]])

#Column indices 列索引
idx1 = np.array([[[0,2],
                  [0,2]],

                 [[0,2],
                 [0,2]]])

#Depth indices 深度索引
idx2= np.array([[[0,0],
                 [2,2]],

                 [[0,0],
                 [2,2]]])

# Notice that the (0,0,0) element of the sliced array will be (0,0,0,) of arr1,
# (1,0,0) of sliced array will be element (2,0,0) of arr1,
# (0,1,0) of sliced array will be element (0,2,0) of arr1,
# and so on.
print(arr1[idx0,idx1,idx2])#print arr--输出数组

[[['Joey' 'Wayne']
  ['Sarah' 'Liam']]

 [['Wayne' 'Joey']
  ['Lucy' 'Alex']]]


`idx0`指示如何选择第一个坐标，`idx1`指示如何选择第二个坐标，`idx2`指示如何选择第三个坐标。 在这种情况下，我们在原始数组的每个四分之一元素中选择对象。

因此，我实际上已经编写了一些代码，可以实际演示哪些元素将显示在新数组中，即，原始数组中的坐标对新数组中的元素而言是什么。

例如，我们得到的是一个二维矩阵`2 x 2 x 2`。如果我们想知道切片对象的第二个块 第二行、第一列的内容，则可以使用如下代码 ：

In [65]:
# In fact, if you want to know which element of arr1 will be in the sliced array,
# here's some code that will tell you:
# 事实上，如果您想知道arr1的哪个元素将出现在切片数组中，
# 这里有一些代码可以告诉您：

coord =(1,1,0) #Coord in sliced array 坐标在切片数组中
print((idx0[coord],idx1[coord],idx2[coord])) #print(())——输出元组

(2, 0, 2)


那是原始数组的元素 2、0、2。

## 拓展数组
-----------


连接函数允许使用屏幕上显示的语法沿公共轴将数组绑定在一起。 该方法要求数组沿未用于绑定的轴具有相似的形状。 结果就是全新的` ndarray `，这是将数组粘合在一起的产物。 为此，还存在其他类似函数，例如堆叠。 我们不会涵盖所有内容。

假设我们想向` arr2 `添加更多行。 使用以下代码执行此操作：

In [85]:
# 添加新行
# Add a new row
arr2_1 = np.concatenate((arr2, np.array([["Sam","Joe", "Bill"]])), axis=0)
print(arr2_1)

[['Joey' 'Margaret' 'Wayne']
 ['Max' 'Harold' 'Bob']
 ['Wayne' 'Lucy' 'Joey']
 ['Sam' 'Joe' 'Bill']]


我们创建一个全新的数组。 在这种情况下，我们不需要使用`copy`方法。 结果如上

我们在此数组中添加了第四行，将新数组与数据（数组中的名称）绑定在一起。 它仍然是一个二维数组。 例如，请参见以下示例中的数组。 您可以清楚地看到这是二维的，但只有一列，而前一个只有一列，这是我们在此新列中添加后的结果：

In [87]:
# 添加新列
# Add a new column
arr2_2 = np.concatenate((arr2_1, np.array([["Maya"],["Nana"], ["Gus"],["Grey"]])), axis=1)
print(arr2_2)

[['Joey' 'Margaret' 'Wayne' 'Maya']
 ['Max' 'Harold' 'Bob' 'Nana']
 ['Wayne' 'Lucy' 'Joey' 'Gus']
 ['Sam' 'Joe' 'Bill' 'Grey']]


我们将继续对数组进行数学运算。

## 带数组的算术和线性代数
--------------------------
现在，我们已经了解了如何使用 NumPy 数组创建和访问信息，让我们介绍一下可以对数组执行的一些数值运算。 在本节中，我们将讨论使用 NumPy 数组的算法。 我们还将讨论将 NumPy 数组用于线性代数。

## 两个形状相等的数组的算术
---------------------------
NumPy 数组的算术总是按组件进行的。 这意味着，如果我们有两个形状相同的矩阵，则通过匹配两个矩阵中的相应分量并将它们相加来完成诸如加法之类的操作。 对于任何算术运算都是如此，无论是加法，减法，乘法，除法，幂，甚至是逻辑运算符。

让我们来看一个例子。 首先，我们创建两个随机数据数组：

In [9]:
import numpy as np
from numpy.random import randn
import numpy.linalg as ln

arr1 = np.array(randn(3,3,3)*10, dtype=np.int64)
arr2 = np.array(randn(3,3,3)*10, dtype=np.int64)
print(arr1)

[[[  84  160  -18]
  [ -56  -71    0]
  [-122   -7  -65]]

 [[-105   -6    0]
  [-166  108  103]
  [ 112  -90   23]]

 [[ -25  -45   20]
  [-158   50   11]
  [  76  -11   43]]]


In [10]:
print(arr2)

[[[  8  -9  -5]
  [ 10 -13  -8]
  [ 25  -8   8]]

 [[ 11 -13 -31]
  [  6  -1   3]
  [ 23  11   6]]

 [[-11   5   0]
  [  2   2   5]
  [ -5   9   2]]]


虽然我用涉及两个数组的算术方式解释了这些想法，但正如我们在此处看到的那样，它可能涉及数组和标量，我们将`100`添加到`arr1`中的每个元素中：

In [11]:
print(arr1 + 100)

[[[184 260  82]
  [ 44  29 100]
  [-22  93  35]]

 [[ -5  94 100]
  [-66 208 203]
  [212  10 123]]

 [[ 75  55 120]
  [-58 150 111]
  [176  89 143]]]


In [12]:
# 接下来，我们将arr1中的每个元素除以2：
print(arr1 / 2)

[[[ 42.   80.   -9. ]
  [-28.  -35.5   0. ]
  [-61.   -3.5 -32.5]]

 [[-52.5  -3.    0. ]
  [-83.   54.   51.5]
  [ 56.  -45.   11.5]]

 [[-12.5 -22.5  10. ]
  [-79.   25.    5.5]
  [ 38.   -5.5  21.5]]]


In [13]:
# 接下来，将arr1中的每个元素提升为2的幂：
print(arr1 ** 2)

[[[ 7056 25600   324]
  [ 3136  5041     0]
  [14884    49  4225]]

 [[11025    36     0]
  [27556 11664 10609]
  [12544  8100   529]]

 [[  625  2025   400]
  [24964  2500   121]
  [ 5776   121  1849]]]


In [14]:
# 接下来，我们将arr1和arr2的内容相乘：
print(arr1 * arr2)

[[[  672 -1440    90]
  [ -560   923     0]
  [-3050    56  -520]]

 [[-1155    78     0]
  [ -996  -108   309]
  [ 2576  -990   138]]

 [[  275  -225     0]
  [ -316   100    55]
  [ -380   -99    86]]]


请注意，arr1和arr2的形状相似。在这里，我们进行了涉及这两个数组的更复杂的计算：

In [15]:
print(arr1 ** (arr2 / 4))  # Watch out for nan and inf!

[[[7.05600000e+03 1.09832290e-05            nan]
  [           nan            nan            inf]
  [           nan 2.04081633e-02 4.22500000e+03]]

 [[           nan            nan            inf]
  [           nan 3.10201620e-01 3.23316537e+01]
  [6.06741401e+11            nan 1.10304125e+02]]

 [[           nan            nan 1.00000000e+00]
  [           nan 7.07106781e+00 2.00327632e+01]
  [4.45638814e-03            nan 6.55743852e+00]]]


C:\Users\10071\AppData\Local\Temp\ipykernel_1856\3861567326.py:1: RuntimeWarning: divide by zero encountered in power
  print(arr1 ** (arr2 / 4))  # Watch out for nan and inf!
C:\Users\10071\AppData\Local\Temp\ipykernel_1856\3861567326.py:1: RuntimeWarning: invalid value encountered in power
  print(arr1 ** (arr2 / 4))  # Watch out for nan and inf!


注意，此计算最终产生了`inf`和`nan`。

## 广播
--------------
到目前为止，我们已经处理了两个形状相同的数组。 实际上，这不是必需的。 尽管我们不一定要添加两个任意形状的数组，但是在某些情况下，我们可以合理地对不同形状的数组执行算术运算。 从某种意义上说，较小数组中的信息被视为属于相同形状但具有重复值的数组。 让我们看看实际的广播行为。

现在，回想一下数组`arr1`为`3 x 3 x 3`； 也就是说，它具有三行，三列和三个平板。 在这里，我们创建一个对象`arr3`：

In [38]:
# 生成一个形状为(1,1,3)，第一列和第三列为0的随机整数数组
# Generate a random integer array with shape (1,1,3), with the first column and the third column as 0
arr3 = np.array(randn(1,1,3)*10, dtype=np.int64)
arr3[:, :, 0] = 0
arr3[:, :, 2] = 0
arr3[:, :, 1] = 1   # Set the middle column to 1
print(arr3)
print(arr3.shape)

[[[0 1 0]]]
(1, 1, 3)


该对象的形状为`(1, 1, 3)`。 因此，此对象的平板数与`arr1`相同，但只有一行和一列。 这是可以应用广播的情况； 实际上，这是结果：

In [39]:
print(arr1 * arr3)

[[[  0 160   0]
  [  0 -71   0]
  [  0  -7   0]]

 [[  0  -6   0]
  [  0 108   0]
  [  0 -90   0]]

 [[  0 -45   0]
  [  0  50   0]
  [  0 -11   0]]]


我将第`0`列和第`2`列设为`0`，将中间列设为`1`。因此，结果是我有效地选择了中间列并将其他两列设置为`0`。有效地复制了该对象，因此好像我将`arr1`乘以一个对象一样，其中第一列为`0`，第三列为`0`，第二列为`1`。

现在，让我们看看如果切换此对象的尺寸会发生什么？ 因此，现在它具有一列，一个平板和三行：

In [40]:
arr4 = arr3.transpose((0,2, 1))
print(arr4)

[[[0]
  [1]
  [0]]]


In [41]:
# 结果如下
print(arr1 * arr4)

[[[   0    0    0]
  [ -56  -71    0]
  [   0    0    0]]

 [[   0    0    0]
  [-166  108  103]
  [   0    0    0]]

 [[   0    0    0]
  [-158   50   11]
  [   0    0    0]]]


现在，让我们进行另一个换位。 我们将最终将一个具有三个平板的对象相乘，中间的平板由`1`填充。 因此，当我进行乘法运算时，会发生以下情况：

In [42]:
arr5 = arr3.transpose((2,0, 1))
print(arr5)

[[[0]]

 [[1]]

 [[0]]]


In [43]:
print(arr1 * arr5)

[[[   0    0    0]
  [   0    0    0]
  [   0    0    0]]

 [[-105   -6    0]
  [-166  108  103]
  [ 112  -90   23]]

 [[   0    0    0]
  [   0    0    0]
  [   0    0    0]]]
